SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS DNA_EXTRACT_RECORD_ITEM;
DROP TABLE IF EXISTS DNA_EXTRACT_RECORD;




/* Create Tables */

-- 提取室
CREATE TABLE DNA_EXTRACT_RECORD
(
	ID VARCHAR(64) NOT NULL COMMENT 'id',
	CODE VARCHAR(255) COMMENT '编码',
	LAB_ID VARCHAR(64) COMMENT '实验室id',
	EQUIPMENT_ID VARCHAR(64) COMMENT '设备ID',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	TEMPERATURE VARCHAR(255) COMMENT '温度',
	HUMIDITY VARCHAR(255) COMMENT '相对湿度',
	REFRIGERATOR_TEMPERATURE VARCHAR(255) COMMENT '冰箱温度',
	BEFORE_TRIAL VARCHAR(255) COMMENT '实验前',
	INSTRUMENT_USE VARCHAR(255) COMMENT '仪器设备使用',
	BIOSAFETY_CABINET VARCHAR(255) COMMENT '生物安全柜/超净台',
	FINAL_TEMPLATE VARCHAR(255) COMMENT '最后模版溶液体积',
	EXTRACTED_TEMPLATE VARCHAR(255) COMMENT '提取的模板存放处',
	HEATING_PROCESS VARCHAR(255) COMMENT '加热过程',
	STORAGE_TEMPERATURE VARCHAR(255) COMMENT '存放温度',
	EXTRACTORS VARCHAR(255) COMMENT '提取者',
	REVIEWER VARCHAR(255) COMMENT '复核人',
	TRANSFER_TEMPLATE VARCHAR(255) COMMENT '模板交接',
	RECIPIENT VARCHAR(255) COMMENT '接收人',
	TEMPLATE_HANDOVER_DATE	 VARCHAR(255) COMMENT '模板交接日期',
	OTHER VARCHAR(255) COMMENT '其他',
	OTHERONE VARCHAR(255) COMMENT '其他1',
	OTHERTOW VARCHAR(255) COMMENT '其他2',
	OTHERTR VARCHAR(255) COMMENT '其它3',
	OTHERFOUR VARCHAR(255) COMMENT '其它4',
	OTHERFIVE VARCHAR(255) COMMENT '其它5',
	PRIMARY KEY (ID)
) COMMENT = '提取室';


-- 提取室详情
CREATE TABLE DNA_EXTRACT_RECORD_ITEM
(
	ID VARCHAR(64) NOT NULL COMMENT 'id',
	RECORD_ID VARCHAR(64) NOT NULL COMMENT 'record_id',
	EXTRACT_ROUNDS VARCHAR(255) COMMENT '提取轮次',
	SAMPLE_NUMBER VARCHAR(255) COMMENT '样品编号',
	CHECK_TYPES VARCHAR(255) COMMENT '检材类型',
	BASED_AMOUNT VARCHAR(255) COMMENT '取材量',
	BASED_AMOUNT_OTHER VARCHAR(255) COMMENT '取材量其他',
	EXTRACT_WAY VARCHAR(255) COMMENT '提取方式',
	EXTRACT_WAYOTHER VARCHAR(255) COMMENT '提取方式其他',
	REAGENT_BATCHES VARCHAR(255) COMMENT '试剂批号',
	EXTRACTION_METHOD VARCHAR(255) COMMENT '核酸抽提方法',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '提取室详情';



/* Create Foreign Keys */

ALTER TABLE DNA_EXTRACT_RECORD_ITEM
	ADD FOREIGN KEY (RECORD_ID)
	REFERENCES DNA_EXTRACT_RECORD (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



