SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ENTRUST_EXPERT_OPINION;




/* Create Tables */

CREATE TABLE ENTRUST_EXPERT_OPINION
(
	ID VARCHAR(64) NOT NULL,
	REGISTER_ID VARCHAR(64),
	VERSION INT,
	-- 第一鉴定人
	DRAFTER VARCHAR(255) COMMENT '第一鉴定人',
	-- 初稿
	DRAFT_TIME DATETIME COMMENT '初稿',
	DRAFT TEXT,
	-- 初稿说明
	DRAFT_REMARK TEXT COMMENT '初稿说明',
	-- 第二鉴定人
	SECONDER VARCHAR(255) COMMENT '第二鉴定人',
	SECOND_REMARK TEXT,
	SECOND_TIME DATETIME,
	-- 签字授权人
	DIRECTOR VARCHAR(255) COMMENT '签字授权人',
	DIRECTOR_REMARK TEXT,
	DIRECTOR_TIME DATETIME,
	FINALER VARCHAR(255),
	-- 终版
	FINAL_VERSION TEXT COMMENT '终版',
	FINAL_TIME DATETIME,
	PRIMARY KEY (ID)
);



