SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS SYNTH_EQUIPMENT_USAGE_RECORD;
DROP TABLE IF EXISTS SYNTH_EQUIPMENT;
DROP TABLE IF EXISTS SYNTH_GOODS_STOCK;
DROP TABLE IF EXISTS SYNTH_GOODS;
DROP TABLE IF EXISTS SYNTH_GOODS_CATEGORY;
DROP TABLE IF EXISTS SYNTH_LAB_DISINFECT_RECORD;
DROP TABLE IF EXISTS SYNTH_LAB_INSPECT_RECORD;
DROP TABLE IF EXISTS SYNTH_LAB_USAGE_RECORD;
DROP TABLE IF EXISTS SYNTH_LAB;




/* Create Tables */

-- 设备管理
CREATE TABLE SYNTH_EQUIPMENT
(
	ID VARCHAR(64) NOT NULL,
	LAB_ID VARCHAR(64) NOT NULL,
	-- 编码
	CODE VARCHAR(255) COMMENT '编码',
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 采购时间
	PURCHASE_TIME DATETIME COMMENT '采购时间',
	-- 生产厂家
	MANUFACTURER VARCHAR(255) COMMENT '生产厂家',
	-- 经销商
	DEALER VARCHAR(255) COMMENT '经销商',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '设备管理';


-- 设备使用记录
CREATE TABLE SYNTH_EQUIPMENT_USAGE_RECORD
(
	ID VARCHAR(64) NOT NULL,
	EQUIPMENT_ID VARCHAR(64) NOT NULL,
	-- 使用人
	OPERATOR_ID VARCHAR(64) COMMENT '使用人',
	-- 使用时间
	OPERATE_DATE DATETIME COMMENT '使用时间',
	REGISTER_ID VARCHAR(64),
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '设备使用记录';


-- 药品信息
CREATE TABLE SYNTH_GOODS
(
	ID VARCHAR(64) NOT NULL,
	-- 编码
	CODE VARCHAR(255) COMMENT '编码',
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 规格
	SPECIFICATION VARCHAR(255) COMMENT '规格',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	CATEGORY_ID VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
) COMMENT = '药品信息';


-- 药品分类
CREATE TABLE SYNTH_GOODS_CATEGORY
(
	ID VARCHAR(64) NOT NULL,
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '药品分类';


-- 药品库存信息
CREATE TABLE SYNTH_GOODS_STOCK
(
	ID VARCHAR(64) NOT NULL,
	GOODS_ID VARCHAR(64) NOT NULL,
	BATCH_NUMBER VARCHAR(255),
	MANUFACTURER VARCHAR(255),
	QTY DOUBLE,
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '药品库存信息';


-- 实验室
CREATE TABLE SYNTH_LAB
(
	ID VARCHAR(64) NOT NULL,
	-- 编码
	CODE VARCHAR(255) COMMENT '编码',
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '实验室';


-- 实验室消毒记录
CREATE TABLE SYNTH_LAB_DISINFECT_RECORD
(
	ID VARCHAR(64) NOT NULL,
	LAB_ID VARCHAR(64) NOT NULL,
	-- 使用人
	OPERATOR_ID VARCHAR(64) COMMENT '使用人',
	-- 使用时间
	OPERATE_DATE DATETIME COMMENT '使用时间',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '实验室消毒记录';


-- 实验室检查记录
CREATE TABLE SYNTH_LAB_INSPECT_RECORD
(
	ID VARCHAR(64) NOT NULL,
	LAB_ID VARCHAR(64) NOT NULL,
	-- 温度
	TEMPERATURE VARCHAR(255) COMMENT '温度',
	WETNESS VARCHAR(255),
	INSPECT_TIME DATETIME,
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '实验室检查记录';


-- 实验室使用记录
CREATE TABLE SYNTH_LAB_USAGE_RECORD
(
	ID VARCHAR(64) NOT NULL,
	LAB_ID VARCHAR(64) NOT NULL,
	-- 使用人
	OPERATOR_ID VARCHAR(64) COMMENT '使用人',
	-- 使用时间
	OPERATE_DATE DATETIME COMMENT '使用时间',
	REGISTER_ID VARCHAR(64),
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '实验室使用记录';



/* Create Foreign Keys */

ALTER TABLE SYNTH_EQUIPMENT_USAGE_RECORD
	ADD FOREIGN KEY (EQUIPMENT_ID)
	REFERENCES SYNTH_EQUIPMENT (ID)
	
	
;


ALTER TABLE SYNTH_GOODS_STOCK
	ADD FOREIGN KEY (GOODS_ID)
	REFERENCES SYNTH_GOODS (ID)
	
	
;


ALTER TABLE SYNTH_GOODS
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES SYNTH_GOODS_CATEGORY (ID)
	
	
;


ALTER TABLE SYNTH_EQUIPMENT
	ADD FOREIGN KEY (LAB_ID)
	REFERENCES SYNTH_LAB (ID)
	
	
;


ALTER TABLE SYNTH_LAB_DISINFECT_RECORD
	ADD FOREIGN KEY (LAB_ID)
	REFERENCES SYNTH_LAB (ID)
	
	
;


ALTER TABLE SYNTH_LAB_INSPECT_RECORD
	ADD FOREIGN KEY (LAB_ID)
	REFERENCES SYNTH_LAB (ID)
	
	
;


ALTER TABLE SYNTH_LAB_USAGE_RECORD
	ADD FOREIGN KEY (LAB_ID)
	REFERENCES SYNTH_LAB (ID)
	
	
;



